# Generated by Django 5.1.6 on 2025-06-16 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Adevetinta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('an_universitar', models.CharField(max_length=9)),
                ('an_studiu', models.IntegerField()),
                ('specializare', models.CharField(max_length=150)),
                ('tip_taxa', models.CharField(choices=[('fara taxa', 'Fara Taxa'), ('cu taxa', 'Cu Taxa')], max_length=9)),
                ('motiv', models.TextField()),
                ('data_emitere', models.DateField(auto_now_add=True)),
                ('numar', models.IntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In Process'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='in_progress', max_length=12)),
                ('pdf_link', models.CharField(blank=True, max_length=500, null=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Specializare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=150)),
                ('facultate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializari', to='api.facultate')),
            ],
        ),
        migrations.CreateModel(
            name='Grupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an_universitar', models.CharField(max_length=9)),
                ('an_studiu', models.IntegerField()),
                ('grupa', models.IntegerField()),
                ('semigrupa', models.CharField(max_length=1)),
                ('facultate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupe', to='api.facultate')),
                ('specializare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupe', to='api.specializare')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_student', models.IntegerField()),
                ('semigrupa', models.CharField(max_length=1)),
                ('tip_taxa', models.CharField(choices=[('fara taxa', 'Fara Taxa'), ('cu taxa', 'Cu Taxa')], max_length=9)),
                ('an_universitar', models.CharField(max_length=9)),
                ('an_studiu', models.IntegerField()),
                ('is_2fa_enable', models.BooleanField(default=False)),
                ('totp_secret_key', models.CharField(blank=True, max_length=32, null=True)),
                ('totp_enable_at', models.DateTimeField(blank=True, null=True)),
                ('is_2fa_verified', models.BooleanField(default=False)),
                ('facultate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.facultate')),
                ('grupa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupa')),
                ('specializare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.specializare')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
